steps:
  # Load environment variables from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create a temporary .env file with secrets from Secret Manager
        echo "DATABASE_URL=$(gcloud secrets versions access latest --secret=expensesplitter-database-url)" >> .env
        echo "SESSION_SECRET=$(gcloud secrets versions access latest --secret=expensesplitter-session-secret)" >> .env
        echo "RESEND_API_KEY=$(gcloud secrets versions access latest --secret=expensesplitter-resend-api-key)" >> .env
        echo "CURRENCY_API_KEY=$(gcloud secrets versions access latest --secret=expensesplitter-currency-api-key)" >> .env
        echo "DEBUG=False" >> .env
        echo "ALLOWED_HOSTS=*.run.app" >> .env

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Load environment variables from .env file
        export $(grep -v '^#' .env | xargs)

        # Deploy to Cloud Run with environment variables
        gcloud run deploy expensesplitter \
          --source . \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "DATABASE_URL=${DATABASE_URL},SESSION_SECRET=${SESSION_SECRET},DEBUG=${DEBUG},RESEND_API_KEY=${RESEND_API_KEY},CURRENCY_API_KEY=${CURRENCY_API_KEY},ALLOWED_HOSTS=${ALLOWED_HOSTS}"

        # Remove the temporary .env file
        rm .env
